# Generated by Django 4.2.5 on 2023-11-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_text_post_en_us_post_text_post_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_post_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_post_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
